import Head from 'next/head'
import { Lato } from 'next/font/google'


const lato = Lato({ 
  subsets: ['latin'],
  weight: ['400', '700'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Painting Budget</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello world!</h1>
    </>
  )
}
